<a href="https://colab.research.google.com/github/shibataryoma22-hub/-udemy/blob/main/basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

データの操作を可能にする
多次元配列をサポート

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5]) #配列の作成
print(a)

[1 2 3 4 5]


In [4]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [5]:
c = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


形状の変換

In [6]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a.shape)

(2, 3)


In [8]:
#配列の形状の変換
b = np.array([0 ,1, 2, 3, 4, 5, 6, 7])
c = b.reshape(2, 4)
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [10]:
d = np.array([[[0, 1, 2], [3, 4, 5]],
              [[5, 4, 3], [2, 1, 0]]])
print(d)
e = d.reshape(-1)
print(e)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]
[0 1 2 3 4 5 5 4 3 2 1 0]


要素へのアクセス

In [11]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a[2])

2


In [12]:
#要素の入れ替え
a[2] = 9
print(a)

[0 1 9 3 4 5]


２次元配列の場合、[行列で指定]

In [13]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b[1, 2])

5


In [14]:
b[1, 2] = 9
print(b)

[[0 1 2]
 [3 4 9]]


関数の引数や返り値としてnumpyの配列を使用することができる


In [15]:
def my_func(x):
  y = x * 2 + 1
  return y
a = np.array([[0, 1, 2], [3, 4, 5]])
b = my_func(a)
print(b)

[[ 1  3  5]
 [ 7  9 11]]


In [16]:
b = np.array([[0, 1, 2], [3, 4, 5]])

print(np.sum(b))
print(np.average(b))
print(np.max(b))
print(np.min(b))

15
2.5
5
0


In [18]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(np.sum(b, axis = 0)) #縦方向での合計
print(np.sum(b, axis = 1)) #横方向での合計

[3 5 7]
[ 3 12]
